### ISSUE TITLE
NoMethodError when ELB's dns_name is used

### ISSUE THREAD

**Issue by ossphilips** [srbartlett/elbow#4]
gems/elbow-0.0.6/lib/elbow/capistrano_v2.rb:10:in `elastic_load_balancer': undefined method`cname' for nil:NilClass (NoMethodError)

**Comment by ossphilips** [comment]
(tested with Capistrano V2)

**Comment by linko** [comment]
I'm having the same issue on capistrano v2. And this fix works for me. Thanks!

@srbartlett Why don't merge it?

**Comment by srbartlett** [comment]
Merged. Thanks for the feedback.
